name: auto-key production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo building the app

  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://chaveiroautokey.com.br
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Hostinger Production
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{vars.REMOTE_HOST}}
          REMOTE_USER: ${{vars.REMOTE_USER}}
          REMOTE_PORT: ${{vars.REMOTE_PORT}}
          TARGET: ${{vars.TARGET}}
