name: Deploy para o Servidor

on:
  push:
    branches: [ "main" ]  # ou "master", dependendo do seu repositório

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Conectar via SSH e fazer deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_IP }}
          username: marcio
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/chaveiroautokey
            git pull origin main
            npm run build
            cp -r dist/* /var/www/chaveiroautokey/
