name: Deploy para o Servidor

on:
  push:
    branches: [ "main" ]  # ou "master", dependendo do seu repositório

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Conectar via SSH e fazer deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_IP }}
          username: marcio
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /home/marcio
          
            if [ -d site ]; then
            cd site && git pull origin main
            else
            git clone git@github.com:masbsoft-dev/auto-key.git site
            cd site
            fi
          
            npm install
            npm run build
            sudo rm -rf /var/www/chaveiroautokey/*
            sudo cp -r dist/* /var/www/chaveiroautokey/

